# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataPicker.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from MyQLabel import MyQLabel
from MyImageShow import MyImageShow

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(732, 374)
        MainWindow.setMaximumSize(QtCore.QSize(800, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BoxImage = MyImageShow(self.centralwidget)
        self.BoxImage.setGeometry(QtCore.QRect(9, 9, 301, 291))
        self.BoxImage.setAutoFillBackground(False)
        self.BoxImage.setFrameShape(QtWidgets.QFrame.Panel)
        self.BoxImage.setText("")
        self.BoxImage.setObjectName("BoxImage")
        self.BoxProb = MyQLabel(self.centralwidget)
        self.BoxProb.setGeometry(QtCore.QRect(315, 10, 120, 120))
        self.BoxProb.setFrameShape(QtWidgets.QFrame.Box)
        self.BoxProb.setText("")
        self.BoxProb.setObjectName("BoxProb")
        self.BtnOrigin = QtWidgets.QPushButton(self.centralwidget)
        self.BtnOrigin.setGeometry(QtCore.QRect(454, 17, 75, 23))
        self.BtnOrigin.setObjectName("BtnOrigin")
        self.BtnMaxX = QtWidgets.QPushButton(self.centralwidget)
        self.BtnMaxX.setGeometry(QtCore.QRect(549, 17, 75, 23))
        self.BtnMaxX.setObjectName("BtnMaxX")
        self.BtnMaxY = QtWidgets.QPushButton(self.centralwidget)
        self.BtnMaxY.setGeometry(QtCore.QRect(639, 17, 75, 23))
        self.BtnMaxY.setObjectName("BtnMaxY")
        self.ListData = QtWidgets.QListWidget(self.centralwidget)
        self.ListData.setGeometry(QtCore.QRect(313, 135, 121, 165))
        self.ListData.setObjectName("ListData")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(454, 70, 33, 16))
        self.label_3.setObjectName("label_3")
        self.EditStartX = QtWidgets.QLineEdit(self.centralwidget)
        self.EditStartX.setGeometry(QtCore.QRect(495, 70, 78, 20))
        self.EditStartX.setObjectName("EditStartX")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(579, 70, 27, 16))
        self.label_4.setObjectName("label_4")
        self.EditEndX = QtWidgets.QLineEdit(self.centralwidget)
        self.EditEndX.setGeometry(QtCore.QRect(619, 70, 95, 20))
        self.EditEndX.setObjectName("EditEndX")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(454, 100, 33, 16))
        self.label_5.setObjectName("label_5")
        self.EditStartY = QtWidgets.QLineEdit(self.centralwidget)
        self.EditStartY.setGeometry(QtCore.QRect(495, 100, 78, 20))
        self.EditStartY.setObjectName("EditStartY")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(579, 100, 27, 16))
        self.label_6.setObjectName("label_6")
        self.EditEndY = QtWidgets.QLineEdit(self.centralwidget)
        self.EditEndY.setGeometry(QtCore.QRect(619, 100, 95, 20))
        self.EditEndY.setObjectName("EditEndY")
        self.BtnClockwise = QtWidgets.QPushButton(self.centralwidget)
        self.BtnClockwise.setGeometry(QtCore.QRect(100, 310, 75, 23))
        self.BtnClockwise.setMinimumSize(QtCore.QSize(0, 0))
        self.BtnClockwise.setObjectName("BtnClockwise")
        self.BtnLoadImage = QtWidgets.QPushButton(self.centralwidget)
        self.BtnLoadImage.setGeometry(QtCore.QRect(10, 310, 75, 23))
        self.BtnLoadImage.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.BtnLoadImage.setFont(font)
        self.BtnLoadImage.setObjectName("BtnLoadImage")
        self.BtnAntiClockwise = QtWidgets.QPushButton(self.centralwidget)
        self.BtnAntiClockwise.setGeometry(QtCore.QRect(190, 310, 89, 23))
        self.BtnAntiClockwise.setMinimumSize(QtCore.QSize(0, 0))
        self.BtnAntiClockwise.setObjectName("BtnAntiClockwise")
        self.BtnStart = QtWidgets.QPushButton(self.centralwidget)
        self.BtnStart.setGeometry(QtCore.QRect(539, 180, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.BtnStart.setFont(font)
        self.BtnStart.setObjectName("BtnStart")
        self.BtnOneStepBack = QtWidgets.QPushButton(self.centralwidget)
        self.BtnOneStepBack.setGeometry(QtCore.QRect(303, 310, 81, 23))
        self.BtnOneStepBack.setObjectName("BtnOneStepBack")
        self.BtnExport2File = QtWidgets.QPushButton(self.centralwidget)
        self.BtnExport2File.setGeometry(QtCore.QRect(390, 310, 81, 23))
        self.BtnExport2File.setObjectName("BtnExport2File")
        self.SliderZoom = QtWidgets.QSlider(self.centralwidget)
        self.SliderZoom.setGeometry(QtCore.QRect(310, 10, 13, 120))
        self.SliderZoom.setOrientation(QtCore.Qt.Vertical)
        self.SliderZoom.setObjectName("SliderZoom")
        self.SliderZoom.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 732, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BtnOrigin.setText(_translate("MainWindow", "Coord Origin"))
        self.BtnMaxX.setText(_translate("MainWindow", "Max X"))
        self.BtnMaxY.setText(_translate("MainWindow", "Max Y"))
        self.label_3.setText(_translate("MainWindow", "Start X"))
        self.label_4.setText(_translate("MainWindow", "End X"))
        self.label_5.setText(_translate("MainWindow", "Start Y"))
        self.label_6.setText(_translate("MainWindow", "End Y"))
        self.BtnClockwise.setText(_translate("MainWindow", "1° Clockwise"))
        self.BtnLoadImage.setText(_translate("MainWindow", "Load Image"))
        self.BtnAntiClockwise.setText(_translate("MainWindow", "1° Anti-clockwise"))
        self.BtnStart.setText(_translate("MainWindow", "Start"))
        self.BtnOneStepBack.setText(_translate("MainWindow", "One Step Back"))
        self.BtnExport2File.setText(_translate("MainWindow", "Export to File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

